name: Run main.py script

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to scrape'
        required: true
      webhook_url:
        description: 'Webhook URL to send results'
        required: true
        default: 'https://backend.vezhdelit.com/api/webhook/scraped-html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Execute py script
        # Pass the workflow input 'url' as an environment variable named GITHUB_INPUT_URL
        env:
          GITHUB_INPUT_URL: ${{ github.event.inputs.url }}
          GITHUB_INPUT_WEBHOOK_URL: ${{ github.event.inputs.webhook_url }}
        run: python main.py

